# https://github.com/hatena/renovate-config/blob/687964addf81a21051571d09a4829af43bc00ab4/.github/workflows/validate-config.yml
name: Validate renovate config

on:
  push:
    branches: [main]
  pull_request:

env:
  # renovate: datasource=node-version depName=node
  NODE_VERSION: '24.21.0'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      CI: true

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version: '${{ env.NODE_VERSION }}'
      - uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node
      - name: Validate renovate config
        run: |
          for file in *.json*
          do
            echo "[CI] Let's validate $file"
            RENOVATE_CONFIG_FILE=${file} npx --package renovate -c 'renovate-config-validator'
          done
